#include <key_def.h>

struct key_state key_matrix_state[KEY_NUM_COLUMN][KEY_NUM_ROW] = { 0 };

const enum key_matrix key_matrix[KEY_NUM_COLUMN][KEY_NUM_ROW] = {
    { KEY_ESC, KEY_BACKTICK, KEY_TAB, KEY_CAPS_LOCK, KEY_INVALID, KEY_LEFT_CONTROL },
    { KEY_INVALID, KEY_ONE, KEY_INVALID, KEY_INVALID, KEY_LEFT_SHIFT, KEY_LEFT_SUPER },
    { KEY_F1, KEY_TWO, KEY_Q, KEY_A, KEY_Z, KEY_INVALID },
    { KEY_F2, KEY_THREE, KEY_W, KEY_S, KEY_X, KEY_LEFT_ALT },
    { KEY_F3, KEY_FOUR, KEY_E, KEY_D, KEY_C, KEY_INVALID },
    { KEY_F4, KEY_FIVE, KEY_R, KEY_F, KEY_V, KEY_INVALID },
    { KEY_INVALID, KEY_SIX, KEY_T, KEY_G, KEY_B, KEY_SPACE },
    { KEY_F5, KEY_SEVEN, KEY_Y, KEY_H, KEY_N, KEY_INVALID },
    { KEY_F6, KEY_EIGHT, KEY_U, KEY_J, KEY_M, KEY_INVALID },
    { KEY_F7, KEY_NINE, KEY_I, KEY_K, KEY_COMMA, KEY_INVALID },
    { KEY_F8, KEY_ZERO, KEY_O, KEY_L, KEY_PERIOD, KEY_RIGHT_ALT },
    { KEY_F9, KEY_MINUS, KEY_P, KEY_SEMICOLON, KEY_SLASH, KEY_RIGHT_SUPER },
    { KEY_F10, KEY_PLUS, KEY_LEFT_SQUARE, KEY_APOSTROPHE, KEY_INVALID, KEY_INVALID },
    { KEY_F11, KEY_INVALID, KEY_RIGHT_SQUARE, KEY_RIGHT_SHIFT, KEY_ENTER, KEY_RIGHT_FN },
    { KEY_F12, KEY_BACKSPACE, KEY_BACKSLASH, KEY_INVALID, KEY_INVALID, KEY_RIGHT_CONTROL },
    { KEY_PRINT_SCREEN, KEY_INSERT, KEY_DELETE, KEY_INVALID, KEY_INVALID, KEY_LEFT_ARROW },
    { KEY_SCROLL_LOCK, KEY_HOME, KEY_END, KEY_INVALID, KEY_UP_ARROW, KEY_DOWN_ARROW },
    { KEY_PAUSE, KEY_PAGE_UP, KEY_PAGE_DOWN, KEY_INVALID, KEY_INVALID, KEY_RIGHT_ARROW },
    { KEY_INVALID, KEY_NUM_LOCK, KEY_NUMPAD_SEVEN, KEY_NUMPAD_FOUR, KEY_NUMPAD_ONE, KEY_NUMPAD_ZERO },
    { KEY_INVALID, KEY_NUMPAD_DIVIDE, KEY_NUMPAD_EIGHT, KEY_NUMPAD_FIVE, KEY_NUMPAD_TWO, KEY_INVALID },
    { KEY_INVALID, KEY_NUMPAD_MULTIPLY, KEY_NUMPAD_NINE, KEY_NUMPAD_SIX, KEY_NUMPAD_THREE, KEY_NUMPAD_PERIOD },
    { KEY_INVALID, KEY_NUMPAD_MINUS, KEY_NUMPAD_PLUS, KEY_INVALID, KEY_NUMPAD_ENTER, KEY_INVALID }
};
